version: "3.8"
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - cos4hnet
    ports:
      - 22181:2181
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cos4hnet
  user:
    container_name: user
    build:
      context: ./
      dockerfile: ./Dockerfile.user
    env_file:
      - .env
    depends_on:
      - kafka
    networks:
      - cos4hnet
  order:
    container_name: order
    build:
      context: ./
      dockerfile: ./Dockerfile.order
    env_file:
      - .env
    depends_on:
      - kafka
      - user
    networks:
      - cos4hnet
  product:
    container_name: product
    build:
      context: ./
      dockerfile: ./Dockerfile.product
    env_file:
      - .env
    depends_on:
      - kafka
      - order
      - user
    networks:
      - cos4hnet
  file:
    container_name: file
    build:
      context: ./
      dockerfile: ./Dockerfile.file
    env_file:
      - .env
    depends_on:
      - kafka
      - order
      - user
      - product
    networks:
      - cos4hnet
  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: ./Dockerfile.gateway
    env_file:
      - .env
    depends_on:
      - kafka
      - user
      - order
      - product
      - file
    networks:
      - cos4hnet
    ports:
      - "7777:7777"
networks:
  cos4hnet:
